<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CongregacaoSeeder extends Seeder
{
    public function run(): void
    {
        $congregacoes = [
            'CONGREGAÇÂO ADÃO DO CARMO',
            'CONGREGAÇÂO ALTINOPOLIS',
            'CONGREGAÇÂO ALTINOPOLIS FIGUEREDO VALTER',
            'CONGREGAÇÂO ARCEBURGO',
            'CONGREGAÇÂO ARLINDO LAGUNA',
            'CONGREGAÇÂO BARRINHA COLORADO',
            'CONGREGAÇAO BARRINHA PRESIDENTE VARGAS',
            'CONGREGAÇÂO BARRINHA SUB SEDE',
            'CONGREGAÇÃO BATATAIS SANTA RITA',
            'CONGREGAÇÂO BATATAIS SUB',
            'CONGREGAÇÂO BONFIM PAULISTA',
            'CONGREGAÇÃO BRODOSKI',
            'CONGREGAÇAO BRODOSKI JOAO LUIZ',
            'CONGREGAÇÂO CAJURU',
            'CONGREGAÇÂO CAMPOS ELISEOS',
            'CONGREGAÇÂO CANDIA',
            'CONGREGAÇÂO CASSIA DOS COQUEIROS',
            'CONGREGAÇÂO CHACARA 57',
            'CONGREGAÇÂO CRAVINHOS NOVA CRAVINHOS',
            'CONGREGAÇÂO CRAVINHOS SUBE SEDE',
            'CONGREGAÇÂO CRUZ DAS POSSES',
            'CONGREGAÇÂO DOM MIELLI',
            'CONGREGAÇÂO DUMONT',
            'CONGREGAÇÂO DUTRA 2',
            'CONGREGAÇÂO FLAMBOYANS',
            'CONGREGAÇÂO GREENVILLE',
            'CONGREGAÇÂO GUARANÉSIA',
            'CONGREGAÇÂO GUAXUPÉ',
            'CONGREGAÇÂO IPIRANGA',
            'CONGREGAÇÂO IPUÃ',
            'CONGREGAÇÂO ITUVERAVA',
            'CONGREGAÇAO JARDINÓPOLIS AVENIDA',
            'CONGREGAÇÂO JARDINOPOLIS SAN DOMINGUES',
            'CONGREGAÇÂO JARDINOPOLIS SANTA EMILIA',
            'CONGREGAÇÂO JARDINOPOLIS SUB SEDE',
            'CONGREGAÇÂO JARDINOPOLIS VILA REIS',
            'CONGREGAÇÂO JD AEROPORTO',
            'CONGREGAÇÂO JD CENTENARIO',
            'CONGREGAÇÂO JD INDEPENDENCIA',
            'CONGREGAÇÃO JD IRAJÁ',
            'CONGREGAÇÂO JD MARIA DAS GRAÇAS',
            'CONGREGAÇÂO JD PROGRESSO',
            'CONGREGAÇÂO JD ZARA',
            'CONGREGAÇAO JOQUEI CLUBE',
            'CONGREGAÇÂO JURUAIA',
            'CONGREGAÇÂO JURUCE',
            'CONGREGAÇÂO LAGOINHA',
            'CONGREGAÇÂO LUIZ ANTONIO',
            'CONGREGAÇÂO MARIA CASA GRANDE',
            'CONGREGAÇÂO MOCOCA',
            'CONGREGAÇÂO MONTE ALEGRE',
            'CONGREGAÇÂO MONTE SANTO DE MINAS',
            'CONGREGAÇÂO MORRO AGUDO JD CANADA',
            'CONGREGAÇÂO MORRO AGUDO JD SILVEIRA',
            'CONGREGAÇÂO MORRO AGUDO SUB SEDE',
            'CONGREGAÇÂO NOVA SIMIONE',
            'CONGREGAÇÃO NUPORANGA',
            'CONGREGAÇÂO ORLANDIA',
            'CONGREGAÇAO PAIVA 1',
            'CONGREGAÇAO PAIVA 2',
            'CONGREGAÇÂO PALMEIRAS 2',
            'CONGREGAÇÂO PARQUE DOS PINUS',
            'CONGREGAÇÂO PARQUE DOS SERVIDORES',
            'CONGREGAÇÂO PARQUE RIBERÃO',
            'CONGREGAÇÂO PLANALTO VERDE',
            'CONGREGAÇÃO PONTAL',
            'CONGREGAÇÂO PONTAL CAMPOS ELISIOS',
            'CONGREGAÇÃO PONTAL NOVA PONTAL',
            'CONGREGAÇÂO PONTAL SANTA CATARINA',
            'CONGREGAÇÂO QUINTINO 1',
            'CONGREGAÇÂO QUINTINO 2',
            'CONGREGAÇÂO RECREIO ANHANGUERA',
            'CONGREGAÇÂO RIBERÃO VERDE',
            'CONGREGAÇÂO SALES DE OLIVEIRA',
            'CONGREGAÇÂO SALGADO FILHO 1',
            'CONGREGAÇÂO SANTA CRUZ DA ESPERANCA',
            'CONGREGAÇÂO SANTO ANTONIO DA ALEGRIA',
            'CONGREGAÇÂO SÃO PEDRO DA UNIÃO',
            'CONGREGAÇÂO SÃO SEBASTIÃO DO PARAISO',
            'CONGREGAÇÂO SÃO SIMÃO',
            'CONGREGAÇÂO SEDE IEADERP',
            'CONGREGAÇÂO SERRA AZUL',
            'CONGREGAÇÂO SERRANA',
            'CONGREGAÇÂO VILA ALBERTINA',
            'CONGREGAÇÂO VILA AUGUSTA',
            'CONGREGAÇÂO VILA CARVALHO',
            'CONGREGAÇÂO VILA VIRGINIA',
            'CONGREGAÇÂO VIRADOURO',
        ];

        foreach ($congregacoes as $nome) {
            DB::table('congregacoes')->insert([
                'nome' => $nome,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}